"""Update Stage relationships

Revision ID: 2bf67f5a8539
Revises: 3f3ac33234ad
Create Date: 2024-08-06 10:52:22.239265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf67f5a8539'
down_revision: Union[str, None] = '3f3ac33234ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_level', sa.Column('stage_id', sa.Integer(), nullable=True))
    op.alter_column('player_level', 'score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=True)
    op.create_foreign_key(None, 'player_level', 'stage', ['stage_id'], ['id'])
    op.add_column('player_story', sa.Column('stage_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'player_story', 'stage', ['stage_id'], ['id'])
    op.drop_constraint('room_id_stage_fkey', 'room', type_='foreignkey')
    op.drop_column('room', 'id_stage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('id_stage', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('room_id_stage_fkey', 'room', 'stage', ['id_stage'], ['id'])
    op.drop_constraint(None, 'player_story', type_='foreignkey')
    op.drop_column('player_story', 'stage_id')
    op.drop_constraint(None, 'player_level', type_='foreignkey')
    op.alter_column('player_level', 'score',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('player_level', 'stage_id')
    # ### end Alembic commands ###
