"""Initial migration

Revision ID: 31ed38235345
Revises: 0d5bf913cfa7
Create Date: 2024-07-25 23:05:18.639717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31ed38235345'
down_revision: Union[str, None] = '0d5bf913cfa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('educational_entity', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('educational_entity', 'code',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.drop_index('ix_educational_entity_code', table_name='educational_entity')
    op.drop_constraint('player_special_need_id_fkey', 'player', type_='foreignkey')
    op.alter_column('player_level', 'score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=True)
    op.alter_column('special_need', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_index('ix_special_need_name', table_name='special_need')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_special_need_name', 'special_need', ['name'], unique=False)
    op.alter_column('special_need', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('player_level', 'score',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.create_foreign_key('player_special_need_id_fkey', 'player', 'special_need', ['special_need_id'], ['id'])
    op.create_index('ix_educational_entity_code', 'educational_entity', ['code'], unique=True)
    op.alter_column('educational_entity', 'code',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('educational_entity', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###
