"""Add state column to player_level and player_story

Revision ID: 3f3ac33234ad
Revises: a153d55d706d
Create Date: 2024-08-04 14:43:55.812338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f3ac33234ad'
down_revision: Union[str, None] = 'a153d55d706d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_level', sa.Column('state', sa.String(length=64), nullable=True))
    op.alter_column('player_level', 'score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=True)
    op.add_column('player_story', sa.Column('state', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_story', 'state')
    op.alter_column('player_level', 'score',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('player_level', 'state')
    # ### end Alembic commands ###
