"""Descripción de la migración

Revision ID: 48f82991c01c
Revises: 755f0bab51fa
Create Date: 2024-08-19 02:20:41.757779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48f82991c01c'
down_revision: Union[str, None] = '755f0bab51fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'password')
    op.drop_column('player', 'user_name')
    op.alter_column('player_level', 'score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_level', 'score',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.add_column('player', sa.Column('user_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('player', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
