"""Initial migration

Revision ID: f76974c6c1ff
Revises: 35eb0d56c0be
Create Date: 2024-07-25 23:08:55.353915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f76974c6c1ff'
down_revision: Union[str, None] = '35eb0d56c0be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'player', 'special_need', ['special_need_id'], ['id'])
    op.drop_column('player', 'special_need')
    op.alter_column('player_level', 'score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_level', 'score',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.add_column('player', sa.Column('special_need', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'player', type_='foreignkey')
    # ### end Alembic commands ###
