from db.base_class import Base
from models.user_role import UserRole
from models.dashboard_user import DashboardUser
from models.player import Player
from models.caretaker_player import CaretakerPlayer
from models.course import Course
from models.educational_entity import EducationalEntity
from models.game import Game
from models.chapter import Chapter
from models.level import Level
from models.education_reviewer import EducationReviewer
from models.special_need import SpecialNeed
from models.skills import Skills
from models.avatar import Avatar
from models.course_player import CoursePlayer
from models.story import Story
from models.player_story import PlayerStory
from models.player_special_need import PlayerSpecialNeed
from models.level_skills import LevelSkills
from models.player_level import PlayerLevel
from models.stage import Stage
from models.room import Room
from models.country import Country
from models.politic_division import PoliticDivision
from models.city import City
